run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - gosimple
    - staticcheck
    - unused

linters-settings:
  gofmt:
    simplify: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - site/node_modules
